version: "3.9"
services:
  web:
    image: nginx:latest
    depends_on:
      - db
      - php
    ports:
      - "8080:80"
    volumes:
      - ./nginx-html/public:/usr/share/nginx/html
      - ./nginx-html/config:/etc/nginx/conf.d/
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
  php:
    build: ./php
    volumes:
      - ./nginx-html/public:/usr/share/nginx/html

volumes:
  db-data:
